import {
  buildFallbackBodyBlock,
  computeRangeInputHashBlock,
  type ProjectRangeSummary,
  type RangeSummaryPersistedProvider,
} from '@/services/lego_blocks/units/aiActivityRangeSummaryBlock'
import {
  getProjectRangeSummaryBlock,
  putProjectRangeSummaryBlock,
} from '@/services/lego_blocks/integrations/aiActivityRangeSummaryStoreBlock'
import {
  getAiActivityRangeSummaryProvider,
  type AiActivityRangeSummaryProvider,
} from '@/services/lego_blocks/units/storageKeyBlock'
import { runContract } from '@/services/orchestrators/intelligenceOrch'
import {
  rangeLabelContract,
  type RangeLabelChainInput,
  type RangeLabelContractInput,
  type RangeLabelOutput,
} from '@/services/lego_blocks/units/intelligence/contracts/rangeLabelContractBlock'
import {
  rangeNarrateContract,
  type RangeNarrateArcInput,
  type RangeNarrateChainInput,
  type RangeNarrateContractInput,
  type RangeNarrateOutput,
} from '@/services/lego_blocks/units/intelligence/contracts/rangeNarrateContractBlock'
import {
  rangeSummaryContract,
  type RangeSummaryContractInput,
  type RangeSummaryOutput,
} from '@/services/lego_blocks/units/intelligence/contracts/rangeSummaryContractBlock'

// Public surface: `ensureRangeSummaryOrch(input)` returns a persisted
// ProjectRangeSummary tagged with whichever path actually ran.
//
// Provider selection is user-driven (Settings → AI Activity → Range summary
// provider). Three modes:
//   'off'         → build deterministic body (titles list, or count stub if
//                   titles are absent). No model calls.
//   'local'       → two-stage: label + cluster + narrate on the default
//                   intelligence provider.
//   'claude-cli'  → one-shot on the claude-cli provider.
//
// Both non-off paths fall through to the deterministic fallback on failure,
// and the persisted record's `provider` field records what actually ran so
// the UI can badge "generated by X" or "deterministic".

// Bump these when the corresponding prompt is meaningfully changed — the
// range hash includes them so cached bodies invalidate.
const LOCAL_PIPELINE_PROMPT_VERSION = 1
const CLAUDE_PIPELINE_PROMPT_VERSION = 1
const FALLBACK_PROMPT_VERSION = 1

const MISC_MIN_FRAC = 0.05
const MISC_MIN_MS = 10 * 60_000
const MAX_ARCS_LOCAL = 5

const MONTH_SHORT = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
function fmtDate(iso: string): string {
  const parts = iso.split('-')
  if (parts.length !== 3) return iso
  return `${MONTH_SHORT[Number(parts[1]) - 1]} ${Number(parts[2])}`
}
function fmtDateSpan(startIso: string, endIso: string): string {
  return startIso === endIso ? `on ${fmtDate(startIso)}` : `across ${fmtDate(startIso)} → ${fmtDate(endIso)}`
}
function humanDuration(ms: number): string {
  const totalMinutes = Math.max(1, Math.round(ms / 60_000))
  const h = Math.floor(totalMinutes / 60)
  const m = totalMinutes % 60
  if (h === 0) return `${m}m`
  if (m === 0) return `${h}h`
  return `${h}h ${m}m`
}
function firstBulletOfSummary(summary: string): string {
  if (!summary) return ''
  const m = /^1[.)]\s*(.+?)(?:\n2[.)]|$)/s.exec(summary)
  if (m) return m[1].split('\n').join(' ').trim().slice(0, 300)
  return summary.split('\n').filter(Boolean)[0]?.slice(0, 300) ?? ''
}

// ── Input shape ─────────────────────────────────────────────────────────

export interface RangeSummaryDigestInput {
  chainKey: string
  date: string
  startedIso: string
  endedIso: string
  title: string
  summary: string
  durationMs: number
  msgCount: number
}

export interface EnsureRangeSummaryInput {
  projectId: string
  projectLabel?: string
  rangeStartDate: string
  rangeEndDate: string
  chains: RangeSummaryDigestInput[]
  /** Optional force override for the provider (e.g. a manual "refresh with
   *  Claude" button). When absent, the user's saved preference is used. */
  providerOverride?: AiActivityRangeSummaryProvider
  /** When true, ignore any cached record and re-run. */
  refresh?: boolean
}

// ── Public entry ────────────────────────────────────────────────────────

export async function ensureRangeSummaryOrch(
  input: EnsureRangeSummaryInput,
): Promise<ProjectRangeSummary> {
  const provider = input.providerOverride ?? getAiActivityRangeSummaryProvider()
  const promptVersion =
    provider === 'local'
      ? LOCAL_PIPELINE_PROMPT_VERSION
      : provider === 'claude-cli'
        ? CLAUDE_PIPELINE_PROMPT_VERSION
        : FALLBACK_PROMPT_VERSION
  const inputHash = computeRangeInputHashBlock({
    chains: input.chains.map(c => ({ chainKey: c.chainKey, date: c.date, durationMs: c.durationMs })),
    promptVersion,
    provider,
  })

  if (!input.refresh) {
    const existing = await getProjectRangeSummaryBlock(
      input.projectId,
      input.rangeStartDate,
      input.rangeEndDate,
    )
    if (existing && existing.inputHash === inputHash) return existing
  }

  const generated = await generateForProvider(provider, input)
  await putProjectRangeSummaryBlock({ ...generated, inputHash })
  return { ...generated, inputHash }
}

/** Read-only variant — returns whatever is currently persisted (or null),
 *  never triggers generation. Used by surfaces that want to reflect state
 *  without kicking off model calls. */
export async function loadRangeSummaryOrch(
  projectId: string,
  rangeStartDate: string,
  rangeEndDate: string,
): Promise<ProjectRangeSummary | null> {
  return getProjectRangeSummaryBlock(projectId, rangeStartDate, rangeEndDate)
}

// ── Provider dispatch ───────────────────────────────────────────────────

async function generateForProvider(
  provider: AiActivityRangeSummaryProvider,
  input: EnsureRangeSummaryInput,
): Promise<ProjectRangeSummary> {
  if (provider === 'off') return buildFallbackSummary(input)
  if (provider === 'local') return generateLocalTwoStage(input)
  if (provider === 'claude-cli') return generateClaudeOneShot(input)
  return buildFallbackSummary(input)
}

function totalDurationMs(chains: RangeSummaryDigestInput[]): number {
  return chains.reduce((n, c) => n + c.durationMs, 0)
}

function baseSummary(input: EnsureRangeSummaryInput): Omit<ProjectRangeSummary, 'body' | 'provider' | 'model'> {
  const totalMs = totalDurationMs(input.chains)
  return {
    schemaVersion: 1,
    projectId: input.projectId,
    rangeStartDate: input.rangeStartDate,
    rangeEndDate: input.rangeEndDate,
    chainKeys: input.chains.map(c => c.chainKey).sort(),
    totalDurationMs: totalMs,
    inputHash: '', // filled by caller after provider selection
    generatedAt: new Date().toISOString(),
  }
}

function buildFallbackSummary(input: EnsureRangeSummaryInput): ProjectRangeSummary {
  const { body, provider } = buildFallbackBodyBlock(input.chains)
  return { ...baseSummary(input), body, provider, model: '' }
}

// ── Local two-stage path ────────────────────────────────────────────────

async function generateLocalTwoStage(input: EnsureRangeSummaryInput): Promise<ProjectRangeSummary> {
  if (input.chains.length === 0) return buildFallbackSummary(input)

  // Stage 1: label
  const labelChains: RangeLabelChainInput[] = input.chains.map((c, i) => ({
    chainKey: c.chainKey,
    shortKey: `S${i + 1}`,
    title: c.title,
    firstBulletHint: firstBulletOfSummary(c.summary),
  }))
  const labelInput: RangeLabelContractInput = {
    projectId: input.projectId,
    projectLabel: input.projectLabel,
    rangeStartDate: input.rangeStartDate,
    rangeEndDate: input.rangeEndDate,
    chains: labelChains,
  }
  const labelResult = await runContract(rangeLabelContract, labelInput)
  if (!labelResult.ok || !labelResult.value) return buildFallbackSummary(input)
  // Contract-typed generics through `runContract` widen to `{}`; the contract's
  // finalize returns RangeLabelOutput, so this cast is safe.
  const labelValue = labelResult.value as RangeLabelOutput

  // Stage 2: deterministic cluster
  const themeNameByShort = new Map<string, string>()
  for (const c of labelChains) {
    const themeIdx = labelValue.assignments[c.shortKey]
    const name = themeIdx ? labelValue.themes[themeIdx - 1] : 'Misc'
    themeNameByShort.set(c.shortKey, name || 'Misc')
  }
  const buckets = new Map<string, { label: string; chains: RangeSummaryDigestInput[]; shorts: string[] }>()
  input.chains.forEach((chain, i) => {
    const short = `S${i + 1}`
    const label = themeNameByShort.get(short) || 'Misc'
    const key = label.toLowerCase().trim()
    let b = buckets.get(key)
    if (!b) {
      b = { label, chains: [], shorts: [] }
      buckets.set(key, b)
    }
    b.chains.push(chain)
    b.shorts.push(short)
  })

  const rangeTotalMs = totalDurationMs(input.chains)
  const arcCandidates: Array<{ label: string; chains: RangeSummaryDigestInput[]; totalMs: number }> = []
  const miscCandidates: Array<{ label: string; chains: RangeSummaryDigestInput[]; totalMs: number }> = []
  for (const b of buckets.values()) {
    const totalMs = b.chains.reduce((n, c) => n + c.durationMs, 0)
    const frac = rangeTotalMs > 0 ? totalMs / rangeTotalMs : 0
    const isMiscLabel = b.label.trim().toLowerCase() === 'misc'
    if (isMiscLabel || totalMs < MISC_MIN_MS || frac < MISC_MIN_FRAC) {
      miscCandidates.push({ label: b.label, chains: b.chains, totalMs })
    } else {
      arcCandidates.push({ label: b.label, chains: b.chains, totalMs })
    }
  }
  arcCandidates.sort((a, b) => b.totalMs - a.totalMs)
  if (arcCandidates.length > MAX_ARCS_LOCAL) {
    miscCandidates.push(...arcCandidates.splice(MAX_ARCS_LOCAL))
  }

  const narrateArcs: RangeNarrateArcInput[] = arcCandidates.map(a => {
    const dates = a.chains.map(c => c.date).sort()
    const chains: RangeNarrateChainInput[] = a.chains.map(c => ({
      chainKey: c.chainKey,
      title: c.title,
      summary: c.summary,
      date: c.date,
      durationMs: c.durationMs,
      msgCount: c.msgCount,
      startedIso: c.startedIso,
      endedIso: c.endedIso,
    }))
    return {
      themeLabel: a.label,
      sessionCount: a.chains.length,
      dateSpan: fmtDateSpan(dates[0], dates[dates.length - 1]),
      totalDuration: humanDuration(a.totalMs),
      chains,
    }
  })
  const narrateMisc = miscCandidates.flatMap(m =>
    m.chains.map(c => ({
      title: c.title,
      date: c.date,
      duration: humanDuration(c.durationMs),
      firstBulletHint: firstBulletOfSummary(c.summary),
    })),
  )

  // Empty arc set (labeler misfired) → fallback instead of an empty summary.
  if (narrateArcs.length === 0) return buildFallbackSummary(input)

  // Stage 3: narrate
  const narrateInput: RangeNarrateContractInput = {
    projectId: input.projectId,
    projectLabel: input.projectLabel,
    rangeStartDate: input.rangeStartDate,
    rangeEndDate: input.rangeEndDate,
    totalChains: input.chains.length,
    totalDuration: humanDuration(rangeTotalMs),
    uniqueDays: new Set(input.chains.map(c => c.date)).size,
    arcs: narrateArcs,
    misc: narrateMisc,
  }
  const narrateResult = await runContract(rangeNarrateContract, narrateInput)
  if (!narrateResult.ok || !narrateResult.value) return buildFallbackSummary(input)
  const narrateValue = narrateResult.value as RangeNarrateOutput
  if (!narrateValue.body) return buildFallbackSummary(input)

  return {
    ...baseSummary(input),
    body: narrateValue.body,
    provider: 'local-two-stage' satisfies RangeSummaryPersistedProvider,
    model: (narrateResult.meta?.model as string) ?? narrateResult.model ?? 'unknown',
  }
}

// ── Claude one-shot path ────────────────────────────────────────────────

async function generateClaudeOneShot(input: EnsureRangeSummaryInput): Promise<ProjectRangeSummary> {
  if (input.chains.length === 0) return buildFallbackSummary(input)
  const oneShotInput: RangeSummaryContractInput = {
    projectId: input.projectId,
    projectLabel: input.projectLabel,
    rangeStartDate: input.rangeStartDate,
    rangeEndDate: input.rangeEndDate,
    chains: input.chains.map(c => ({
      chainKey: c.chainKey,
      date: c.date,
      startedIso: c.startedIso,
      endedIso: c.endedIso,
      title: c.title,
      summary: c.summary,
      durationMs: c.durationMs,
      msgCount: c.msgCount,
    })),
  }
  const result = await runContract(rangeSummaryContract, oneShotInput, { provider: 'claude-cli' })
  if (!result.ok || !result.value) return buildFallbackSummary(input)
  const value = result.value as RangeSummaryOutput
  if (!value.body) return buildFallbackSummary(input)
  return {
    ...baseSummary(input),
    body: value.body,
    provider: 'claude-cli' satisfies RangeSummaryPersistedProvider,
    model: (result.meta?.model as string) ?? result.model ?? 'claude-cli',
  }
}
