import { getVaultFS, type VaultFS } from '@/services/lego_blocks/integrations/fsBlock'
import {
  AI_ACTIVITY_RANGE_SUMMARY_CACHE_TASK_ID,
  parseRangeSummaryJsonBlock,
  parseRangeSummaryMarkdownBlock,
  rangeSummaryCacheKeyBlock,
  rangeSummaryVaultRelPathBlock,
  stringifyRangeSummaryJsonBlock,
  stringifyRangeSummaryMarkdownBlock,
  type ProjectRangeSummary,
} from '@/services/lego_blocks/units/aiActivityRangeSummaryBlock'
import {
  intelligenceCacheAvailableBlock,
  readIntelligenceCacheBlock,
  writeIntelligenceCacheBlock,
} from '@/services/lego_blocks/integrations/intelligence/intelligenceCacheBlock'
import { getVaultWriteAiActivityEnabled } from '@/services/lego_blocks/units/vaultWritePrefsBlock'

// Two-tier store, same shape the chain-digest store uses:
//   fast path: intelligence-cache sidecar JSON
//   durable path (opt-in via getVaultWriteAiActivityEnabled): vault markdown
//     mirror at <vaultRoot>/ai-activity/ranges/<projectId>/<start>--<end>.md
// The vault MD includes the provider tag in frontmatter so a reader can
// filter or re-render "generated by claude" vs "local" without re-hydrating
// the sidecar.

async function ensureVaultDir(fs: VaultFS, dir: string): Promise<void> {
  const segments = dir.split('/').filter(Boolean)
  let prefix = ''
  for (const seg of segments) {
    prefix = prefix ? `${prefix}/${seg}` : seg
    try {
      if (!(await fs.exists(prefix))) await fs.mkdir(prefix)
    } catch {
      // Concurrent create or already-exists — fine.
    }
  }
}

async function readFromCache(
  projectId: string,
  rangeStartDate: string,
  rangeEndDate: string,
): Promise<ProjectRangeSummary | null> {
  if (!intelligenceCacheAvailableBlock()) return null
  const rec = await readIntelligenceCacheBlock(
    AI_ACTIVITY_RANGE_SUMMARY_CACHE_TASK_ID,
    rangeSummaryCacheKeyBlock(projectId, rangeStartDate, rangeEndDate),
  )
  if (!rec) return null
  return parseRangeSummaryJsonBlock(rec.valueJson)
}

async function readFromVault(
  projectId: string,
  rangeStartDate: string,
  rangeEndDate: string,
): Promise<ProjectRangeSummary | null> {
  const fs = getVaultFS()
  if (!fs) return null
  const relPath = rangeSummaryVaultRelPathBlock(projectId, rangeStartDate, rangeEndDate)
  try {
    if (!(await fs.exists(relPath))) return null
    const raw = await fs.read(relPath)
    return parseRangeSummaryMarkdownBlock(raw)
  } catch {
    return null
  }
}

async function writeToCache(summary: ProjectRangeSummary): Promise<void> {
  if (!intelligenceCacheAvailableBlock()) return
  await writeIntelligenceCacheBlock({
    taskId: AI_ACTIVITY_RANGE_SUMMARY_CACHE_TASK_ID,
    cacheKey: rangeSummaryCacheKeyBlock(summary.projectId, summary.rangeStartDate, summary.rangeEndDate),
    providerId: `ai-activity-range-summary:${summary.provider}`,
    model: summary.model || summary.provider,
    generatedAt: summary.generatedAt,
    valueJson: stringifyRangeSummaryJsonBlock(summary),
  })
}

async function writeToVault(summary: ProjectRangeSummary): Promise<void> {
  const enabled = await getVaultWriteAiActivityEnabled()
  if (!enabled) return
  const fs = getVaultFS()
  if (!fs) return
  const relPath = rangeSummaryVaultRelPathBlock(summary.projectId, summary.rangeStartDate, summary.rangeEndDate)
  const dir = relPath.slice(0, relPath.lastIndexOf('/'))
  try {
    await ensureVaultDir(fs, dir)
    await fs.write(relPath, stringifyRangeSummaryMarkdownBlock(summary))
  } catch {
    // Best-effort — cache is the source of truth.
  }
}

export async function getProjectRangeSummaryBlock(
  projectId: string,
  rangeStartDate: string,
  rangeEndDate: string,
): Promise<ProjectRangeSummary | null> {
  const cached = await readFromCache(projectId, rangeStartDate, rangeEndDate)
  if (cached) return cached
  const fromVault = await readFromVault(projectId, rangeStartDate, rangeEndDate)
  if (fromVault) {
    // Warm cache so subsequent hits skip the vault.
    await writeToCache(fromVault)
    return fromVault
  }
  return null
}

export async function putProjectRangeSummaryBlock(summary: ProjectRangeSummary): Promise<void> {
  await writeToCache(summary)
  await writeToVault(summary)
}
