import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/lego_blocks/units/ui/card'
import { Switch } from '@/components/lego_blocks/units/ui/switch'
import {
  getAiActivityAiTitlesEnabled,
  setAiActivityAiTitlesEnabled,
} from '@/services/lego_blocks/units/storageKeyBlock'

export default function AiActivityAiTitlesSettingsBlock() {
  const [enabled, setEnabled] = useState<boolean>(() => getAiActivityAiTitlesEnabled())

  const toggle = (checked: boolean) => {
    setAiActivityAiTitlesEnabled(checked)
    setEnabled(checked)
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>AI titles &amp; day summaries</CardTitle>
        <CardDescription>
          When on, chain digests and daily headlines are generated by the
          configured intelligence provider. When off, the app uses a
          deterministic topic-based fallback and never calls the model — even
          if a local model is available.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <label className="flex items-start justify-between gap-4 rounded-md border border-border/60 px-3 py-2.5">
          <div className="min-w-0 space-y-1">
            <div className="text-sm font-medium text-foreground">Generate titles and summaries with AI</div>
            <p className="text-xs text-muted-foreground">
              Independent of provider availability. Turn off to keep the app
              fully deterministic even when a local model is configured.
              Existing stored digests are still shown; new ones fall back until
              you turn it back on.
            </p>
          </div>
          <Switch
            checked={enabled}
            onCheckedChange={toggle}
            aria-label="Generate AI-Activity titles and summaries with AI"
          />
        </label>
      </CardContent>
    </Card>
  )
}
