import { useState } from 'react'
import { SettingsGroupBlock, SettingsRowBlock } from '@/components/lego_blocks/units/SettingsGroupBlock'
import { Switch } from '@/components/lego_blocks/units/ui/switch'
import {
  getAiActivityAiTitlesEnabled,
  setAiActivityAiTitlesEnabled,
} from '@/services/lego_blocks/units/storageKeyBlock'

export default function AiActivityAiTitlesSettingsBlock() {
  const [enabled, setEnabled] = useState<boolean>(() => getAiActivityAiTitlesEnabled())

  const toggle = (checked: boolean) => {
    setAiActivityAiTitlesEnabled(checked)
    setEnabled(checked)
  }

  return (
    <SettingsGroupBlock
      heading="AI titles & day summaries"
      description="When on, chain digests and daily headlines are generated by the configured intelligence provider. When off, the app uses a deterministic topic-based fallback and never calls the model."
    >
      <SettingsRowBlock
        as="label"
        label="Generate titles and summaries with AI"
        description="Independent of provider availability. Existing stored digests are still shown; new ones fall back until you turn it back on."
        control={(
          <Switch
            checked={enabled}
            onCheckedChange={toggle}
            aria-label="Generate AI-Activity titles and summaries with AI"
          />
        )}
      />
    </SettingsGroupBlock>
  )
}
