/**
 * breakQuotesBlock — the "take a break" quote set shown in the late-night moon
 * scene (23:00–05:00). One quote per calendar day, selected deterministically
 * so it stays fixed all day and rotates at local midnight; the set cycles fully
 * every BREAK_QUOTES.length days.
 *
 * Attribution policy: entries with an `author` are ones with a confident,
 * well-documented attribution (or a genuine proverb tradition). The many
 * author-less entries are plain gentle reminders, not attributed quotes — that
 * keeps the set honest instead of pinning shaky names onto aphorisms. A handful
 * of widely-cited-but-uncertain lines are marked "(attributed)".
 */

export interface BreakQuote {
  text: string
  author?: string
}

export const BREAK_QUOTES: readonly BreakQuote[] = Object.freeze([
  // — confident attributions —
  { text: 'Take rest; a field that has rested gives a bountiful crop.', author: 'Ovid' },
  { text: 'Almost everything will work again if you unplug it for a few minutes — including you.', author: 'Anne Lamott' },
  { text: 'Rest is not idleness, and to lie sometimes on the grass on a summer day is by no means a waste of time.', author: 'John Lubbock' },
  { text: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", author: "Ferris Bueller's Day Off" },
  { text: 'Nature does not hurry, yet everything is accomplished.', author: 'Lao Tzu' },
  { text: 'Adopt the pace of nature: her secret is patience.', author: 'Ralph Waldo Emerson' },
  { text: 'Silence is a source of great strength.', author: 'Lao Tzu' },
  { text: 'He who knows that enough is enough will always have enough.', author: 'Lao Tzu' },
  { text: 'A journey of a thousand miles begins with a single step.', author: 'Lao Tzu' },
  { text: 'For fast-acting relief, try slowing down.', author: 'Lily Tomlin' },
  { text: 'It is not enough to be busy; so are the ants. The question is: what are we busy about?', author: 'Henry David Thoreau' },
  { text: 'Our life is frittered away by detail. Simplify, simplify.', author: 'Henry David Thoreau' },
  { text: 'An early-morning walk is a blessing for the whole day.', author: 'Henry David Thoreau' },
  { text: 'Rest is the sweet sauce of labor.', author: 'Plutarch' },
  { text: 'The time to relax is when you don’t have time for it.', author: 'Sydney J. Harris' },
  { text: 'A day of worry is more exhausting than a week of work.', author: 'John Lubbock' },
  { text: 'Sleep is the best meditation.', author: 'Dalai Lama' },
  { text: 'Rest and be thankful.', author: 'William Wordsworth' },
  { text: 'The quieter you become, the more you can hear.', author: 'Ram Dass' },
  { text: 'Wisdom comes with the ability to be still. Just look and listen.', author: 'Eckhart Tolle' },
  { text: 'There is a time for many words, and there is also a time for sleep.', author: 'Homer, The Odyssey' },
  { text: 'Finish each day and be done with it. Tomorrow is a new day.', author: 'Ralph Waldo Emerson' },
  { text: 'Every now and then go away, have a little relaxation; when you return your judgment will be surer.', author: 'Leonardo da Vinci' },
  { text: 'Now and then it’s good to pause in our pursuit of happiness and just be happy.', author: 'Guillaume Apollinaire' },
  { text: 'To do nothing at all is the most difficult thing in the world.', author: 'Oscar Wilde' },
  { text: 'We are all in the gutter, but some of us are looking at the stars.', author: 'Oscar Wilde' },
  { text: 'Smile, breathe, and go slowly.', author: 'Thich Nhat Hanh' },
  { text: 'Walk as if you are kissing the Earth with your feet.', author: 'Thich Nhat Hanh' },
  { text: 'The present moment is filled with joy and happiness. If you are attentive, you will see it.', author: 'Thich Nhat Hanh' },
  { text: 'Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.', author: 'Thich Nhat Hanh' },
  { text: 'Rivers know this: there is no hurry. We shall get there some day.', author: 'A. A. Milne' },
  { text: "Don't underestimate the value of doing nothing.", author: 'A. A. Milne' },
  { text: 'Look up at the stars and not down at your feet.', author: 'Stephen Hawking' },
  { text: 'The sight of the stars makes me dream.', author: 'Vincent van Gogh' },
  { text: 'I have loved the stars too fondly to be fearful of the night.', author: 'Sarah Williams' },
  { text: 'Not all those who wander are lost.', author: 'J. R. R. Tolkien' },
  { text: 'Even the darkest night will end and the sun will rise.', author: 'Victor Hugo' },
  { text: 'Keep close to Nature’s heart, and break clear away, once in a while.', author: 'John Muir' },
  { text: 'The mountains are calling and I must go.', author: 'John Muir' },
  { text: 'In every walk with nature one receives far more than he seeks.', author: 'John Muir' },
  { text: 'To sit in the shade on a fine day and look upon greenery is the most perfect refreshment.', author: 'Jane Austen' },
  { text: 'The best cure for the body is a quiet mind.', author: 'Napoleon Bonaparte' },
  { text: 'The greatest weapon against stress is our ability to choose one thought over another.', author: 'William James' },
  { text: 'This is the real secret of life — to be completely engaged with what you are doing here and now.', author: 'Alan Watts' },
  { text: 'Muddy water is best cleared by leaving it alone.', author: 'Alan Watts' },
  { text: 'You are the sky. Everything else is just the weather.', author: 'Pema Chödrön' },
  { text: 'Within you there is a stillness and a sanctuary to which you can retreat at any time.', author: 'Hermann Hesse' },
  { text: 'In the midst of movement and chaos, keep stillness inside of you.', author: 'Deepak Chopra' },
  { text: 'There is more to life than increasing its speed.', author: 'Mahatma Gandhi' },
  { text: 'Rest is the conversation between what we love to do and how we love to be.', author: 'David Whyte' },
  { text: 'Learn to be quiet enough to hear the genuine within yourself.', author: 'Marian Wright Edelman' },
  { text: 'Sometimes the most important thing in a whole day is the rest we take between two deep breaths.', author: 'Etty Hillesum' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius (attributed)' },
  { text: 'The man who moves a mountain begins by carrying away small stones.', author: 'Confucius (attributed)' },
  { text: 'Everything has beauty, but not everyone sees it.', author: 'Confucius' },
  { text: 'Do not dwell in the past, do not dream of the future; concentrate the mind on the present moment.', author: 'Attributed to the Buddha' },
  { text: 'Peace comes from within. Do not seek it without.', author: 'Attributed to the Buddha' },
  { text: 'Each morning we are born again. What we do today is what matters most.', author: 'Attributed to the Buddha' },
  { text: 'Look deep into nature, and then you will understand everything better.', author: 'Attributed to Albert Einstein' },
  { text: 'And into the forest I go, to lose my mind and find my soul.', author: 'Attributed to John Muir' },
  { text: 'Beware the barrenness of a busy life.', author: 'Attributed to Socrates' },
  { text: 'Doing nothing is better than being busy doing nothing.', author: 'Lao Tzu (attributed)' },
  { text: 'Tension is who you think you should be. Relaxation is who you are.', author: 'Chinese proverb' },
  { text: 'When the winds of change blow, some build walls and others build windmills.', author: 'Chinese proverb' },
  { text: 'A good laugh and a long sleep are the two best cures for anything.', author: 'Irish proverb' },
  { text: 'You will never plow a field if you only turn it over in your mind.', author: 'Irish proverb' },
  { text: 'Fall seven times, stand up eight.', author: 'Japanese proverb' },
  { text: 'The bamboo that bends is stronger than the oak that resists.', author: 'Japanese proverb' },
  { text: 'One kind word can warm three winter months.', author: 'Japanese proverb' },
  { text: 'Vision without action is a daydream. Action without rest is a nightmare.', author: 'Japanese proverb' },
  { text: 'Sit quietly, doing nothing, and spring comes, and the grass grows by itself.', author: 'Zen proverb' },
  { text: 'When walking, walk. When eating, eat.', author: 'Zen proverb' },
  { text: 'The obstacle is the path.', author: 'Zen proverb' },
  { text: 'Let go, or be dragged.', author: 'Zen proverb' },
  { text: 'Muddy water, let stand, becomes clear.', author: 'Zen proverb' },
  { text: 'After the ecstasy, the laundry.', author: 'Zen proverb' },
  { text: 'The quieter you become, the more you are able to hear.', author: 'Zen proverb' },
  { text: 'Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.', author: 'Zen proverb' },

  // — gentle reminders (unattributed) —
  { text: 'Close the laptop. The world will keep spinning.' },
  { text: "You've done enough for today. Truly." },
  { text: 'Breathe in for four. Hold for four. Out for six. Again.' },
  { text: 'Rest is productive too.' },
  { text: 'The work will be there tomorrow. So will you — if you rest.' },
  { text: 'Step away from the screen. Go find a window.' },
  { text: 'Drink a glass of water. Roll your shoulders back.' },
  { text: 'Your best ideas often arrive after you stop chasing them.' },
  { text: "It's late. Be gentle with yourself." },
  { text: 'Tomorrow-you will thank tonight-you for sleeping.' },
  { text: 'A tired mind makes poor decisions. Rest first, decide later.' },
  { text: 'You are allowed to pause.' },
  { text: 'Nothing important will break if you take ten minutes.' },
  { text: 'Unclench your jaw. Drop your shoulders. Breathe.' },
  { text: 'The night is for resting, not for solving everything.' },
  { text: 'Let the day be finished. You did what you could.' },
  { text: 'Slow is smooth, and smooth is fast.' },
  { text: 'Even the moon takes the night off from the sun.' },
  { text: 'Put it down. Pick it up in the morning.' },
  { text: "Rest is not quitting — it's how you keep going." },
  { text: 'The cursor will still blink tomorrow.' },
  { text: 'Give your eyes a horizon to look at.' },
  { text: "You don't have to earn your rest." },
  { text: 'Stillness is where clarity lives.' },
  { text: 'One thing at a time. Right now, that thing is rest.' },
  { text: 'Great work needs a rested mind.' },
  { text: 'The deadline can wait until you’ve slept on it.' },
  { text: 'Walk away. Come back sharper.' },
  { text: 'Let your thoughts settle like snow.' },
  { text: 'The best debugging tool is a good night’s sleep.' },
  { text: 'If you’re reading this at 3am, this is your sign to log off.' },
  { text: 'Progress is not a straight line, and neither is rest.' },
  { text: 'Stretch. Look far away. Blink slowly.' },
  { text: 'You cannot pour from an empty cup.' },
  { text: 'Some problems solve themselves once you stop staring at them.' },
  { text: 'Being busy is not the same as being useful.' },
  { text: 'The most creative act tonight might be closing the tab.' },
  { text: 'Trade one more hour of work for one more hour of sleep.' },
  { text: 'Your worth is not measured in commits.' },
  { text: 'Quiet the notifications. Quiet the mind.' },
  { text: 'A short walk clears more than a long meeting.' },
  { text: 'Rest so hard tomorrow doesn’t have to carry today.' },
  { text: 'Let the tea steep. Let yourself steep too.' },
  { text: 'You are a person, not a process that must always be running.' },
  { text: 'Softly now — the hard part can wait for morning.' },
  { text: 'Half of thinking well is knowing when to stop thinking.' },
  { text: 'The stars came out. Maybe go look at them.' },
  { text: 'Whatever it is, it will look smaller after sleep.' },
  { text: 'Set it down gently. It’s not going anywhere.' },
  { text: 'Tonight, do less. Tomorrow, do it better.' },
  { text: 'A rested no beats an exhausted yes.' },
  { text: 'Your body has been asking for a break for a while now.' },
  { text: 'Perfection can wait. Sleep cannot, forever.' },
  { text: 'Breathe out the day.' },
  { text: 'The screen glow is not the moon. Go find the moon.' },
  { text: 'You made it through today. That counts.' },
  { text: 'Let the last thought of the night be a kind one.' },
  { text: 'Momentum is nice, but so is a pillow.' },
  { text: 'Do not confuse motion with progress. Rest is allowed.' },
  { text: 'The wisest thing you can do right now might be nothing.' },
  { text: 'Give the problem to your subconscious and go to bed.' },
  { text: 'Warm light, warm drink, warm blanket. In that order.' },
  { text: 'You are not behind. You are just tired.' },
  { text: 'Enough for today. Enough is a full sentence.' },
  { text: 'Let the machine idle. You can too.' },
  { text: 'Tomorrow’s you is smarter and rested. Leave it for them.' },
  { text: 'Rest is a decision, not an accident. Decide.' },
  { text: 'The night sky is free and always open. Step outside.' },
  { text: 'Loosen your grip on the day.' },
  { text: 'You don’t have to finish everything tonight. You never did.' },
  { text: 'A calm mind is faster than a frantic one.' },
  { text: 'Let it be unfinished. Beautiful things often are.' },
  { text: 'Sleep is not lost time. It is where the day gets sorted.' },
  { text: 'Put the day down. It’s heavier than you think.' },
  { text: 'Ten slow breaths. Then decide anything.' },
  { text: 'The kindest deadline you can set is bedtime.' },
  { text: 'Small rest now, big clarity later.' },
  { text: 'You are allowed to be a work in progress and still rest.' },
  { text: 'Even lighthouses go dark for part of every turn.' },
  { text: 'Trust that morning is better at hard things.' },
  { text: 'The quiet you’re avoiding is the rest you need.' },
  { text: 'Let your hands stop. Let your mind wander off.' },
  { text: 'Nothing good was ever built by a mind that never slept.' },
  { text: 'Save your work. Save yourself. Log off.' },
  { text: 'The best next step is often a step back.' },
  { text: 'Stars don’t rush. They just keep shining.' },
  { text: 'Let the day close like a book you’ll open tomorrow.' },
  { text: 'Right now, your only task is to slow down.' },
  { text: 'Breathe. This moment is enough.' },
  { text: 'Turn the lights low. Turn the pace low too.' },
  { text: 'You cannot outrun the need to rest. So rest.' },
  { text: 'A gentle night makes a sharper morning.' },
  { text: 'What if you just... stopped, for tonight?' },
  { text: 'Give yourself the same patience you give the loading bar.' },
  { text: 'The moon is up. Consider that permission.' },
  { text: 'Fewer tabs. Deeper breaths.' },
  { text: 'You are more than the thing you did not finish.' },
  { text: 'Rest is how the good ideas find their way back in.' },
  { text: 'Set the tools down. They’ll keep their edge overnight.' },
  { text: 'It is okay for today to simply be over.' },
  { text: 'Long day. Soft night. Let them balance.' },
  { text: 'Your attention is precious. Spend some of it on rest.' },
  { text: 'The most important window open right now is the one to the sky.' },
  { text: 'Be still. The answers like a quiet room.' },
  { text: 'Tonight’s a good night to leave well enough alone.' },
  { text: 'Let the noise settle. Underneath it, you’re fine.' },
  { text: 'Rest is not the reward for the work. It is part of the work.' },
  { text: 'Close your eyes for a moment. The screen can wait.' },
  { text: 'You’ve carried the day far enough. Set it down here.' },
  { text: 'Slow down — everything you’re chasing catches up when you do.' },
  { text: 'A little wonder before sleep goes a long way. Find some.' },
  { text: 'The night asks nothing of you. Accept the offer.' },
  { text: 'Enough screens. Time for stars.' },
  { text: 'Let tomorrow be tomorrow’s problem.' },
  { text: 'You are doing better than the late hour is telling you.' },
  { text: 'Rest like it matters, because it does.' },
  { text: 'Unplug. Unwind. Undo the day, gently.' },
  { text: 'The best thing you can ship tonight is yourself, to bed.' },
  { text: 'Dim the lights. Slow the pace. Rest.' },
  { text: 'You can pick up the thread in the morning. It waits well.' },
  { text: 'Let your shoulders come down from your ears.' },
  { text: 'Whatever’s left undone tonight is a gift to tomorrow’s fresh mind.' },
])

/**
 * The quote for a given day. Deterministic per local calendar date — same
 * quote from midnight to midnight — and cycles through the whole set.
 */
export function quoteForDay(date: Date = new Date()): BreakQuote {
  const startOfDay = new Date(date.getFullYear(), date.getMonth(), date.getDate())
  const dayIndex = Math.floor(startOfDay.getTime() / 86_400_000)
  const len = BREAK_QUOTES.length
  const idx = ((dayIndex % len) + len) % len
  return BREAK_QUOTES[idx]
}
