// Who authored a turn in a native AI transcript.
//
// Both session stores record a *stream of events*, not a list of messages, and
// duration is `last.ts - first.ts` over that stream. Neither store marks who
// caused an event, so the parser used to treat every `isUser` event as "the
// human was here" — which is false for a large fraction of them:
//
//   - Codex injects `<heartbeat>` user turns on a timer to drive automations
//     (`<automation_id>cdmdeid-delta-pull-monitor</automation_id>`). Its own
//     developer preamble says so: "It is not actually sent by the user, but by
//     the system on some interval of time."
//   - Claude Code injects `<task-notification>` when a background task lands.
//   - Claude Code files every tool_result as a `type: "user"` event. In this
//     vault that is 25,140 of ~31,000 user events — 81%.
//
// The cost of not knowing this was not cosmetic. An automation polling Airflow
// every ~10 minutes keeps each inter-event gap under `IDLE_GAP_MS`, so it
// *prevents* the idle split that would have ended the sitting, and the window
// runs on until the automation stops. Measured across both stores that put
// ~35 hours of phantom time on the timeline, with one project (MountSinaiGit)
// inflated 25-29% on each tool independently.
//
// The rule that falls out, and the reason this is one shared block rather than
// two per-source heuristics:
//
//   **Authorship changes only when someone speaks. Everything else inherits.**
//
// A tool result, a caveat, an `<environment_context>`, an `isMeta` preamble and
// an assistant turn are all *continuations* — they carry no authorship of their
// own and ride on whatever turn is in flight. Only a non-empty, non-system user
// body may set the mode. Getting this wrong is not a small error: a literal
// `else { mode = 'human' }` would reset authorship on every tool result, i.e.
// ~25,000 times, and silently re-credit every automated turn to the user.

/** Who caused a turn.
 *
 *  `agent` exists because it is neither of the other two. A Claude Code
 *  sidechain turn is written by the parent agent, so it is not typed by the
 *  human — but it is a subagent doing work the human delegated, and it must
 *  count. Classifying sidechains as continuations dropped 73 subagent-only
 *  transcripts (46 in `frontend`, 23 in `airms-datapilot`, 4 in `App`) as "100%
 *  automation" during development. `agent` and `human` behave identically for
 *  windowing and duration; the split exists so delegated work stays
 *  *attributable* without being *discardable*. */
export type TurnAuthor = 'human' | 'agent' | 'automation' | 'continuation'

/** Turn kinds that count as real work — they anchor windows and own duration. */
export function isWorkAuthorBlock(author: TurnAuthor): boolean {
  return author === 'human' || author === 'agent'
}

/** Codex heartbeat: a timer-driven turn carrying the automation that fired. */
const HEARTBEAT_RE = /^<heartbeat>/
/** Claude Code: the harness waking the agent when a background task lands. */
const TASK_NOTIFICATION_RE = /^<task-notification>/

/** System-injected user turns. Machine-authored, but they say nothing about who
 *  is driving — so they inherit rather than reset. `<environment_context>` is
 *  the one that bites: Codex emits it at session start and at date rollover,
 *  shaped exactly like a user message. There is one sitting in the 10:04pm
 *  MountSinaiGit window immediately after a genuine human turn; treating it as
 *  human would flip the mode back at midnight and credit ten subsequent
 *  heartbeat responses to the user. */
const SYSTEM_PREFIXES = [
  '<environment_context>',
  '<local-command-caveat>',
  '<local-command-stdout>',
  '<command-name>',
  '<command-message>',
  '<user-instructions>',
  '<system-reminder>',
  'Caveat: The messages below were generated by the user while running local commands',
  'You are writing a git commit message',
  'Base directory for this skill:',
]

/** Flags the transcript carries about a user event, when its format has them.
 *  Claude Code writes all three; Codex writes none. */
export interface TurnFlags {
  /** Claude Code `isSidechain` — the turn belongs to a subagent transcript. */
  isSidechain?: boolean
  /** Claude Code `isMeta` — harness-injected (caveats, skill preambles, image
   *  refs). Never typed by the user. */
  isMeta?: boolean
}

/**
 * Classify one user event. `body` must already be flattened to plain text with
 * tool_result / image / reasoning blocks dropped — an empty body therefore
 * means "this event carried no speech", which is exactly the continuation case.
 */
export function classifyUserTurnBlock(body: string, flags: TurnFlags = {}): TurnAuthor {
  const text = body.trim()

  // Order matters. An automation trigger inside a sidechain is still automation,
  // and a heartbeat is still a heartbeat whatever flags ride along with it.
  if (HEARTBEAT_RE.test(text) || TASK_NOTIFICATION_RE.test(text)) return 'automation'

  // No speech → no authorship. This is the tool_result case (81% of Claude Code
  // user events) and it MUST come before any human default.
  if (!text) return 'continuation'

  if (flags.isMeta) return 'continuation'
  for (const p of SYSTEM_PREFIXES) {
    if (text.startsWith(p)) return 'continuation'
  }

  // Delegated work. Checked after the system prefixes so a subagent's own
  // caveats don't register as agent speech.
  if (flags.isSidechain) return 'agent'

  // `[Request interrupted by user]` deliberately lands here: the harness wrote
  // the text, but a human pressing escape is a human being present, and it is
  // the only record that they were.
  return 'human'
}

/** The automation that fired a heartbeat, when the turn names one. Kept so a
 *  surviving session can report *which* automation was running rather than
 *  making the wake invisible — the Derivation contract's "absence is not
 *  evidence" applies to a row we chose not to draw just as much as to a value
 *  we failed to measure. */
export function extractAutomationIdBlock(body: string): string | undefined {
  const m = /<automation_id>\s*([^<\s][^<]*?)\s*<\/automation_id>/.exec(body)
  return m ? m[1] : undefined
}

/**
 * Resolve authorship across a time-ordered event stream.
 *
 * The state machine is the whole idea: walk events in order, let a speaking
 * user turn set the mode, and have everything else inherit it. An assistant
 * event cannot be classified on its own — the same model does the same work
 * whether a human or a cron asked — so its only available signal is what
 * preceded it. Inheritance is not a shortcut here; it is the only sound method.
 *
 * Mutates `events` in place and returns them for chaining.
 */
export function resolveAuthorshipBlock<
  T extends { isUser: boolean; body: string; flags?: TurnFlags; author?: TurnAuthor },
>(events: T[]): T[] {
  // A transcript that opens mid-automation is vanishingly rare, but 'human' is
  // the safer default: it over-counts rather than silently deleting work.
  let mode: TurnAuthor = 'human'
  for (const e of events) {
    if (e.isUser) {
      const author = classifyUserTurnBlock(e.body, e.flags)
      if (author !== 'continuation') mode = author
      e.author = author === 'continuation' ? mode : author
    } else {
      e.author = mode
    }
  }
  return events
}
